version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:17.0.50-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: 
            docker-compose up -d
            docker-compose run dockerskop npm test
      - deploy:
          name: Push app to docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag app_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker tag app_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1