version: '2'
jobs:
  build:
    working_directory: /dockerapp
    docker:
      -image: docker:17.0.50-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
      - run:
          name: Run tests
          command: 
            docker-compose up -d
            docker-compose run dockerskop npm test